# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b18ed22db375d65a08e34b5a883127fe0cc9a23fb76b8150c7384b9eb3bad1d4c8981fe72ed86d946ac10d1bf917d33b4d89f3ad137858fa0068a2461b8b36e3

test:
  secret_key_base: fc160a0cea0f4a61960ba9357082b83ed8c1a3f45a5feff7fdb47ca5bbe6d3694b8c98e3d0a46050b1fbcf035196b85a36d1750e5ff9596451cc0089738c566d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
